name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt -t package/
        cp -R backend/* package/

    # 4. Package the Lambda function
    - name: Package Lambda function
      run: |
        cd package
        zip -r ../lambda_function.zip .
        cd ..

    # 5. Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 6. Deploy to AWS Lambda
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name generate_email_api \
          --zip-file fileb://lambda_function.zip
